
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# HTTPS configurationj with constraint if someone want to tryout my password
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Text to speech
tts:
  - platform: google_translate
  
# alexa
alexa:
  smart_home:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

