alias: Turn on Aqara Light
description: ''
trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: switch_6
      event: 7007
      unique_id: '00:15:8d:00:05:30:49:75'
      device_id: a384c54f05dc3ddca2d3fec184d4bdbb
      gesture: 1
    context:
      user_id:
        - 'null'
condition: []
action:
  - type: turn_on
    device_id: ffd58c4017d1d4e5557c3a718f91d79e
    entity_id: light.aqara_hub_m1s_1293
    domain: light
mode: single

